// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebVRMS.Models;

namespace WebVRMS.Models
{
    public partial interface IVehicleRentalDbContextProcedures
    {
        Task<List<sp_GenerateMonthlyRentalReportsResult>> sp_GenerateMonthlyRentalReportsAsync(DateOnly? StartDate, DateOnly? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
