// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebVRMS.Models;

namespace WebVRMS.Models
{
    public partial class VehicleRentalDbContext
    {
        private IVehicleRentalDbContextProcedures _procedures;

        public virtual IVehicleRentalDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new VehicleRentalDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IVehicleRentalDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class VehicleRentalDbContextProcedures : IVehicleRentalDbContextProcedures
    {
        private readonly VehicleRentalDbContext _context;

        public VehicleRentalDbContextProcedures(VehicleRentalDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_GenerateMonthlyRentalReportsResult>> sp_GenerateMonthlyRentalReportsAsync(DateOnly? StartDate, DateOnly? EndDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StartDate",
                    Value = StartDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "EndDate",
                    Value = EndDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GenerateMonthlyRentalReportsResult>("EXEC @returnValue = [dbo].[sp_GenerateMonthlyRentalReports] @StartDate = @StartDate, @EndDate = @EndDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
